version: '3.8'

services:
  frontend:
    build: ./frontend  # Uses the Dockerfile in the frontend directory
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend  # Uses the Dockerfile in the backend directory
    ports:
      - "5000:5000"
    env_file:
      - .env  # Load environment variables from .env
    depends_on:
      - db

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
